# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sended.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sended_letters(object):
    def setupUi(self, sended_letters):
        sended_letters.setObjectName("sended_letters")
        sended_letters.resize(616, 640)
        self.table_sended = QtWidgets.QTableWidget(sended_letters)
        self.table_sended.setGeometry(QtCore.QRect(10, 10, 591, 511))
        self.table_sended.setObjectName("table_sended")
        self.table_sended.setColumnCount(0)
        self.table_sended.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(sended_letters)
        self.pushButton.setGeometry(QtCore.QRect(510, 540, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(sended_letters)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 540, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(sended_letters)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 590, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(sended_letters)
        QtCore.QMetaObject.connectSlotsByName(sended_letters)

    def retranslateUi(self, sended_letters):
        _translate = QtCore.QCoreApplication.translate
        sended_letters.setWindowTitle(_translate("sended_letters", "Отправленные письма"))
        self.pushButton.setText(_translate("sended_letters", "Архив"))
        self.pushButton_3.setText(_translate("sended_letters", "Узнать статус"))
        self.pushButton_2.setText(_translate("sended_letters", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sended_letters = QtWidgets.QDialog()
    ui = Ui_sended_letters()
    ui.setupUi(sended_letters)
    sended_letters.show()
    sys.exit(app.exec_())
